"""Step 1 of the transcript's two-step risk-reduction plan (§十): a fully
mocked tool backend that proves the veRL-protocol-adapter + reward-loop
wiring works end-to-end WITHOUT any real docker/k8s/API call.

Canned observations are NOT invented here — they are loaded straight from
the same fixtures ``data/cold_start/collect_trajectories.py`` already built
(``data/cold_start/trajectories/mock/*.json``), so there is exactly ONE
mock-trajectory data format in this repo, not two competing ones.

What IS real (never mocked) in this module:
- ``agent.core.remediation.classify_command()`` +
  ``agent.core.hooks.guard_diagnose_ops()`` — re-run against every canned
  Bash command to (re)derive ``hook_decision``/``hook_action``/
  ``hook_target`` for real. This is cheap, pure Python (no docker/k8s
  needed to *call* it); mocking it too would defeat the entire point of a
  reward design whose legitimacy rests on the hook being the real gate
  (see ``rollout_worker.py``'s module docstring and the task's ground-truth
  facts). As a side effect, this also re-derives the SAME values the
  fixture JSON already has (those were themselves generated by calling the
  real hook, in ``collect_trajectories.py::_hook_verdict_for_bash``) — the
  reward-integration test below checks that re-derivation matches, which is
  a live sanity check that this module is really calling the real hook and
  not silently trusting the fixture's stored value.
- ``data/cold_start/signals.py::annotate_steps`` — the same rule-based
  signal-type / repeat-call tagging ``collect_trajectories.py`` uses (single
  shared home for that logic, per its own module docstring).

What IS mocked:
- the actual tool *execution* — no docker/kubectl/curl call ever happens;
  the observation for each canned command is copied verbatim from the
  fixture JSON's ``observation`` field.
"""
from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

from reward.trajectory import Step, Trajectory
from verl_adapter import _repo_paths

DEFAULT_MOCK_TRAJ_DIR = _repo_paths.REPO_ROOT / "data" / "cold_start" / "trajectories" / "mock"
DEFAULT_GROUND_TRUTH_DIR = _repo_paths.REPO_ROOT / "data" / "cold_start" / "ground_truth"


# --------------------------------------------------------------------------
# The one real piece: hook verdicts, computed for real against the (mocked)
# command string.
# --------------------------------------------------------------------------

async def _real_hook_verdict_for_bash_async(command: str) -> dict[str, Any]:
    remediation, guard_diagnose_ops = _repo_paths.load_real_hook_modules()
    input_data = {"tool_name": "Bash", "tool_input": {"command": command}, "hook_event_name": "PreToolUse"}
    result = await guard_diagnose_ops(input_data, "mock-tool-use-id", {})
    decision_raw = (result.get("hookSpecificOutput") or {}).get("permissionDecision")
    decision = decision_raw if decision_raw in ("allow", "deny") else "passthrough"
    verdict = remediation.classify_command(command)
    action = target = None
    if verdict.get("decision") in ("allow", "deny"):
        action, target = verdict.get("action"), verdict.get("target")
    return {"hook_decision": decision, "hook_action": action, "hook_target": target}


def real_hook_verdict_for_bash(command: str) -> dict[str, Any]:
    """Sync wrapper around the real hook check for one Bash command.

    Same algorithm as
    ``data/cold_start/collect_trajectories.py::_hook_verdict_for_bash``
    (that helper is private/underscore-prefixed, so it is deliberately NOT
    imported here — see ``_repo_paths.py``'s module docstring for why); we
    call the same two real functions it calls (``remediation.classify_command``,
    ``guard_diagnose_ops``) directly instead.
    """
    return asyncio.run(_real_hook_verdict_for_bash_async(command))


# --------------------------------------------------------------------------
# Turn-by-turn mocked tool backend — the thing a rollout loop calls.
# --------------------------------------------------------------------------

@dataclass
class MockStepResult:
    observation: str
    hook_decision: str
    hook_action: Optional[str]
    hook_target: Optional[str]


class MockToolBackend:
    """Deterministic, turn-by-turn tool backend for ONE canned scenario.

    A (mocked) veRL rollout loop calls ``execute(tool_name, tool_input)``
    once per sampled tool_call, exactly like it would call a real
    ``verl.tools.base_tool.BaseTool.execute()`` (see
    ``tool_schema_bridge.py``'s module docstring for that contract).

    This class enforces the SAME step order as the fixture file (raises on
    an out-of-order/unexpected call) so a caller can prove the wiring plays
    back a full scenario faithfully, rather than just accepting any input
    silently.
    """

    def __init__(self, raw_steps: list[dict[str, Any]]) -> None:
        self._raw_steps = raw_steps
        self._cursor = 0

    @property
    def exhausted(self) -> bool:
        return self._cursor >= len(self._raw_steps)

    async def execute(self, tool_name: str, tool_input: dict[str, Any]) -> MockStepResult:
        if self.exhausted:
            raise RuntimeError("MockToolBackend: no more canned steps to play back for this scenario")
        expected = self._raw_steps[self._cursor]
        if expected["tool_name"] != tool_name:
            raise ValueError(
                f"MockToolBackend step {self._cursor}: expected tool_name={expected['tool_name']!r}, "
                f"got {tool_name!r} (canned scenarios replay a fixed order)"
            )
        self._cursor += 1
        observation = expected["observation"]  # canned — no real execution ever happens
        if tool_name == "Bash":
            command = str(tool_input.get("command", ""))
            # NOTE: await the async form directly (not the sync `real_hook_verdict_for_bash`
            # wrapper) — this method already runs inside an event loop (driven by
            # `run_mock_rollout`'s own `asyncio.run`), and `asyncio.run` cannot be nested
            # inside a already-running loop.
            verdict = await _real_hook_verdict_for_bash_async(command)  # REAL hook, never mocked
        else:
            # guard_diagnose_ops only inspects tool_name == "Bash" (see
            # AIops-agent/agent/core/hooks.py::_extract_command); every
            # other tool is implicitly passthrough.
            verdict = {"hook_decision": "passthrough", "hook_action": None, "hook_target": None}
        return MockStepResult(observation=observation, **verdict)


# --------------------------------------------------------------------------
# Fixture loading + Trajectory assembly.
# --------------------------------------------------------------------------

def load_raw_mock_trajectory(path: Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _load_ground_truth(alert_id: str, gt_dir: Optional[Path] = None) -> dict[str, Any]:
    """Load ``data/cold_start/ground_truth/<alert_id>.json`` (shape:
    ``{"remediation_type", "suspect_service", "expect_route"}`` — see
    ``data/cold_start/rejection_sample.py``) and translate its field name
    to match ``reward.trajectory.Trajectory.ground_truth``'s contract
    (``"route"``, not ``"expect_route"``). Missing file -> ``{}`` (a
    trajectory with no ground truth is still a structurally valid
    ``Trajectory``; the outcome-reward functions just score 0 for any
    field they can't compare).
    """
    gt_dir = Path(gt_dir) if gt_dir is not None else DEFAULT_GROUND_TRUTH_DIR
    gt_path = gt_dir / f"{alert_id}.json"
    raw = json.loads(gt_path.read_text(encoding="utf-8")) if gt_path.exists() else {}
    out = dict(raw)
    if "expect_route" in out:
        out["route"] = out.pop("expect_route")
    return out


def _translate_post_action_health(raw: Optional[dict[str, Any]]) -> Optional[dict[str, Any]]:
    """Bridge ``collect_trajectories.py``'s mock ``post_action_health`` shape
    (``{"checked", "healthy", "metric", "window_s"}``) into the shape
    ``reward.trajectory.Trajectory`` requires
    (``{"healthy_at_60s", "new_alert_triggered"}``).

    DOCUMENTED JUDGMENT CALL: the two schemas don't line up field-for-field.
    ``checked=False`` (a health probe that was never actually taken) maps to
    ``None`` (matches ``outcome_reward.stop_loss_reward``'s "health check
    missing entirely -> not-recovered bucket" branch, rather than fabricating
    a health verdict that was never taken). The mock fixtures never model a
    "new alert fired during the health window" case, so
    ``new_alert_triggered`` defaults to ``False`` here when absent — a real
    rollout_worker populating this field must read it from an actual second
    alert-firing signal, never default/assume it (see
    ``Trajectory.post_action_health``'s docstring: this must come from a
    real health-check read, never model-authored text).
    """
    if raw is None:
        return None
    if not raw.get("checked", True):
        return None
    return {
        "healthy_at_60s": bool(raw.get("healthy", False)),
        "new_alert_triggered": bool(raw.get("new_alert_triggered", False)),
    }


async def run_mock_rollout(raw_traj: dict[str, Any], gt_dir: Optional[Path] = None) -> Trajectory:
    """Drive ``MockToolBackend`` turn-by-turn through one canned scenario's
    step list, re-deriving hook decisions for real at each turn, then
    assemble a ``reward.trajectory.Trajectory``. This is the function a
    mocked veRL rollout loop would call once per scenario in a real
    integration; here we call it directly since there is no real veRL loop
    in this session to drive it.
    """
    backend = MockToolBackend(raw_traj["steps"])
    steps: list[dict[str, Any]] = []
    for raw_step in raw_traj["steps"]:
        result = await backend.execute(raw_step["tool_name"], raw_step["tool_input"])
        steps.append(
            {
                "tool_name": raw_step["tool_name"],
                "tool_input": raw_step["tool_input"],
                "hook_decision": result.hook_decision,
                "hook_action": result.hook_action,
                "hook_target": result.hook_target,
                "observation": result.observation,
            }
        )

    signals_mod = _repo_paths.load_signals_module()
    signals_mod.annotate_steps(steps)  # fills in signal_types_covered / is_repeat_no_new_info

    ground_truth = _load_ground_truth(raw_traj["alert_id"], gt_dir=gt_dir)
    post_action_health = _translate_post_action_health(raw_traj.get("post_action_health"))

    trajectory_steps = [
        Step(
            tool_name=s["tool_name"],
            tool_input=s["tool_input"],
            hook_decision=s["hook_decision"],
            observation=s["observation"],
            hook_action=s["hook_action"],
            hook_target=s["hook_target"],
            signal_types_covered=s["signal_types_covered"],
            is_repeat_no_new_info=s["is_repeat_no_new_info"],
        )
        for s in steps
    ]
    return Trajectory(
        alert=raw_traj["alert"],
        steps=trajectory_steps,
        final_diagnosis=raw_traj["final_diagnosis"],
        ground_truth=ground_truth,
        route=raw_traj["route"],
        post_action_health=post_action_health,
    )


def load_all_mock_trajectories(
    mock_dir: Optional[Path] = None,
    gt_dir: Optional[Path] = None,
) -> list[Trajectory]:
    """Load every ``data/cold_start/trajectories/mock/*.json`` fixture,
    replay each through ``MockToolBackend``/``run_mock_rollout``, and
    return the resulting ``Trajectory`` objects — ready to feed straight
    into ``reward.step_reward``/``outcome_reward``/``credit_assignment``
    with zero adaptation glue.
    """
    mock_dir = Path(mock_dir) if mock_dir is not None else DEFAULT_MOCK_TRAJ_DIR
    trajectories = []
    for f in sorted(mock_dir.glob("*.json")):
        raw = load_raw_mock_trajectory(f)
        trajectories.append(asyncio.run(run_mock_rollout(raw, gt_dir=gt_dir)))
    return trajectories
